### ISSUE TITLE
SDPDm variance - covariance matrix

### ISSUE THREAD

**Issue by petridin** [RozetaSimonovska/SDPDmod#10]
Good evening, 

first of all congratulations for your nice code and useful functions. I would like to perform a Wald test, for a spatial model using the SDPDm function, yet, in the varcov matrix, I do not know which row/column corresponds to which coefficient. In addition, the std values received from the call of the model (e.g mod$std), do not correspond to the square root of the diagonal var - cov matrix elements. I assume that there is a transformation, but I cannot figure it out. Could you please help me with that?

Thank you in advance and congratulations again on your library, 
Best, 

N.

**Comment by RozetaSimonovska** [comment]
First of all what type of model are you using?
If you have a dynamic model then you should be looking at mod$std1 not mod$std.

If you need a Wald test for tau + rho + eta, that is already implemented and you can see it in mod$Waldt for the statistic and mod$pWald for the p-value

**Comment by petridin** [comment]
Thank you for your reply. I am trying to estimate a dynamic spatial fixed effect model, assuming spatial lag of the dependent variable, Durbin terms and spatial error structure, using the following command in R:

mod5 <- SDPDm(FORMULA2, W = nb2mat(lw$neighbours), data = Data.category2, index = c("ISO.3","TIME_YEARS"), 
model = "sdm",effect = "time",LYtrans = T, dynamic = T, tlaginfo = list(ind = NULL, tl = F, stl = T))

In the model above, I would like to test if the Durbin coefficients are all equal to 0, using the Wald test, and from which I understand is not supported in the SDPDm function. For this reason, I need the names of each row/column of the Variance - Covariance matrix.  In addition, when I compare regression's standard deviations (mod5$std) multiplied by the square root of the countries - years, which are 260: T = 10, N = 26, (sqrt(dim(Data.category2)[1])) with the square root of Variance - Covariance matrix's diagonal elements (sqrt(diag(mod5$varcov))), the results slightly differ. Please see the following values:

> mod5$std*sqrt(dim(Data.category2)[1])
 [1] 4.453614e-03 4.453638e-03 2.923332e-04 4.454181e-03 4.475508e-03 4.930279e-03 4.725072e-03 9.186737e-05 6.769372e-05
[10] 3.061451e-04 4.453976e-03 4.475445e-03 5.409634e-03 4.632248e-03 9.928580e-05 6.578882e-05 
> sqrt(diag(mod5$varcov))  
[1] 4.225069e-03 4.225092e-03 2.773316e-04 4.225607e-03 4.245840e-03 4.677274e-03 4.482597e-03 8.715304e-05 6.421990e-05 
[10] 2.904348e-04 4.225413e-03 4.245780e-03 5.132029e-03 4.394537e-03 9.419078e-05 6.241275e-05 4.225089e-03 1.208737e-06

Thank you again, 
Looking forward to your reply,

N.

**Comment by RozetaSimonovska** [comment]
I think the issue is that you take the dimansion of your original dataset, i.e. n * t=26 * 10. However, in a dynamic model with lag variable not already included in the data (not in tlaginfo = list(ind =)), the dimension of the data used in the spatial model is reduced by 1 timepoint, n*(t-1), so in your case it is 26 * 9.
The names in mod$std and mod$varcov are the same as in mod$coefficients, additionally the second to last is for rho and the last one is for sigma2.

**Comment by petridin** [comment]
Thank you very much for your help and prompt reply!

Best, 

N.

**Comment by petridin** [comment]
Thank you very much for your help and prompt reply. Congratulations again on your project, because it helped me a lot. 

Best, 

N.
