### ISSUE TITLE
Dynamic model specification comparison

### ISSUE THREAD

**Issue by lyhneo** [RozetaSimonovska/SDPDmod#7]
Hi Rozeta,

I notice that you update your "SDPDmod" package recently. I wonder is there any way to calculate Bayesian model comparison criterion from your package? The criterion include DIC (deviance information criterion), WAIC (Widely applicable information criterion) and even Bayesian log likelihood.

Thanks in advance.
Ling

**Comment by RozetaSimonovska** [comment]
Hi Ling,

the criteria that you mention are not implemented in the package.
